# Generated by Django 5.2.7 on 2025-10-23 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sport_branch', models.CharField(help_text='Example: Futsal, Badminton, Basketball', max_length=50)),
                ('location', models.CharField(help_text='Example: South Jakarta', max_length=100)),
                ('contact', models.CharField(help_text='Phone Number or Email', max_length=50)),
                ('experience', models.TextField(blank=True, help_text='Briefly describe the coaching experience')),
                ('certifications', models.TextField(blank=True, help_text='List certifications, separated by commas')),
                ('service_fee', models.CharField(blank=True, help_text='Example: IDR 300,000 / hour', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='coach_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='CoachWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.coach')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'coach')},
            },
        ),
    ]
