# Generated by Django 5.2.7 on 2025-11-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='photo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
