# Generated by Django 5.2.7 on 2025-10-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='certifications',
            field=models.TextField(blank=True, help_text='Sertifikat yang dimiliki oleh Coach, dipisah oleh koma'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='contact',
            field=models.CharField(help_text='Nomor Telepon atau Email', max_length=50),
        ),
        migrations.AlterField(
            model_name='coach',
            name='experience',
            field=models.TextField(blank=True, help_text='Deskripsikan pengalaman Coach'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='location',
            field=models.CharField(help_text='Contoh : Jakarta Selatan, Bandung', max_length=100),
        ),
        migrations.AlterField(
            model_name='coach',
            name='service_fee',
            field=models.CharField(blank=True, help_text='Contoh : RP 300,000 / Jam', max_length=100),
        ),
        migrations.AlterField(
            model_name='coach',
            name='sport_branch',
            field=models.CharField(help_text='Contoh : Sepak Bola, Futsal, Padel', max_length=50),
        ),
    ]
