# Generated by Django 5.2.7 on 2025-10-21 18:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image_url', models.URLField(default='/static/avatar/default_avatar.png')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('olahraga', models.CharField(choices=[('sepakbola', 'Sepak Bola'), ('basket', 'Basket'), ('voli', 'Voli'), ('badminton', 'Badminton'), ('tenis', 'Tenis'), ('futsal', 'Futsal'), ('padel', 'Padel'), ('golf', 'Golf'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20)),
                ('deskripsi', models.TextField()),
                ('kontak', models.CharField(max_length=100)),
                ('tarif_per_jam', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thumbnail', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('olahraga', models.CharField(choices=[('sepakbola', 'Sepak Bola'), ('basket', 'Basket'), ('voli', 'Voli'), ('badminton', 'Badminton'), ('tenis', 'Tenis'), ('futsal', 'Futsal'), ('padel', 'Padel'), ('golf', 'Golf'), ('lainnya', 'Lainnya')], default='update', max_length=20)),
                ('deskripsi', models.TextField()),
                ('tanggal', models.DateField()),
                ('lokasi', models.CharField(max_length=255)),
                ('kontak', models.CharField(max_length=100)),
                ('biaya', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('jam', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lapangan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('olahraga', models.CharField(choices=[('sepakbola', 'Sepak Bola'), ('basket', 'Basket'), ('voli', 'Voli'), ('badminton', 'Badminton'), ('tenis', 'Tenis'), ('futsal', 'Futsal'), ('padel', 'Padel'), ('golf', 'Golf'), ('lainnya', 'Lainnya')], default='update', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('refund', models.BooleanField(default=False)),
                ('tarif_per_sesi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('kecamatan', models.CharField(blank=True, max_length=100, null=True)),
                ('kontak', models.CharField(blank=True, max_length=100, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('peraturan', models.TextField(blank=True, null=True)),
                ('fasilitas', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ManyToManyField(blank=True, to='main.coach')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lapangan', models.ManyToManyField(blank=True, to='main.lapangan')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olahraga_favorit', models.CharField(choices=[('sepakbola', 'Sepak Bola'), ('basket', 'Basket'), ('badminton', 'Badminton'), ('tenis', 'Tenis'), ('futsal', 'Futsal'), ('voli', 'Voli'), ('padel', 'Padel'), ('golf', 'Golf'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20)),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
