# Generated by Django 5.2.6 on 2025-10-08 09:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('olahraga', models.CharField(choices=[('sepakbola', 'Sepak Bola'), ('basket', 'Basket'), ('voli', 'Voli'), ('badminton', 'Badminton'), ('tenis', 'Tenis'), ('futsal', 'Futsal'), ('padel', 'Padel'), ('golf', 'Golf'), ('lainnya', 'Lainnya')], default='update', max_length=20)),
                ('deskripsi', models.TextField()),
                ('kontak', models.CharField(max_length=100)),
                ('tarif_per_jam', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thumbnail', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lapangan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('olahraga', models.CharField(choices=[('sepakbola', 'Sepak Bola'), ('basket', 'Basket'), ('voli', 'Voli'), ('badminton', 'Badminton'), ('tenis', 'Tenis'), ('futsal', 'Futsal'), ('padel', 'Padel'), ('golf', 'Golf'), ('lainnya', 'Lainnya')], default='update', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('refund', models.BooleanField(default=False)),
                ('tarif_per_sesi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kontak', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('review', models.TextField(blank=True, null=True)),
                ('peraturan', models.TextField(blank=True, null=True)),
                ('fasilitas', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
