# Generated by Django 5.2.7 on 2025-10-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='biaya',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
