# Generated by Django 5.2.6 on 2025-10-09 06:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('tanggal', models.DateField()),
                ('lokasi', models.CharField(max_length=255)),
                ('kontak', models.CharField(max_length=100)),
                ('biaya', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('jam', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
