# Generated by Django 5.2.6 on 2025-10-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_event_biaya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='biaya',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
