# Generated by Django 5.2.6 on 2025-10-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='olahraga',
            field=models.CharField(choices=[('sepakbola', 'Sepak Bola'), ('basket', 'Basket'), ('voli', 'Voli'), ('badminton', 'Badminton'), ('tenis', 'Tenis'), ('futsal', 'Futsal'), ('padel', 'Padel'), ('golf', 'Golf'), ('lainnya', 'Lainnya')], default='update', max_length=20),
        ),
    ]
