# Generated by Django 5.2.6 on 2025-10-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_event_olahraga'),
    ]

    operations = [
        migrations.AddField(
            model_name='lapangan',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='olahraga',
            field=models.CharField(choices=[('sepakbola', 'Sepak Bola'), ('basket', 'Basket'), ('voli', 'Voli'), ('badminton', 'Badminton'), ('tenis', 'Tenis'), ('futsal', 'Futsal'), ('padel', 'Padel'), ('golf', 'Golf'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20),
        ),
    ]
