# Generated by Django 5.2.6 on 2025-10-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_lapangan_kecamatan_alter_coach_olahraga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lapangan',
            name='kecamatan',
        ),
        migrations.AlterField(
            model_name='lapangan',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lapangan',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lapangan',
            name='kontak',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
