# Generated by Django 5.2.6 on 2025-10-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_lapangan_kecamatan_alter_lapangan_alamat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lapangan',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
