# Generated by Django 5.2.7 on 2025-10-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
