# Generated by Django 5.2.7 on 2025-10-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_review_session_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
