# Generated by Django 5.2.7 on 2025-10-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='lapangan',
            name='original_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
