# Generated by Django 5.2.7 on 2025-10-22 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0009_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(default='Anonim', max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('review_text', models.TextField()),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('gambar', models.URLField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=255, null=True)),
                ('lapangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.lapangan')),
            ],
            options={
                'ordering': ['-tanggal_dibuat'],
            },
        ),
    ]
